# Travis CI/CD configuration file
branches:
  only:
    - master

pull_request:
  branches:
    - master

language: python
python:
  - "3.9"
#  - "python-nightly"

before_install:
  - curl -sSL https://install.python-poetry.org | python -
  - export PATH="$HOME/.poetry/bin:$PATH"
  - cd $TRAVIS_BUILD_DIR && echo $TRAVIS_BUILD_DIR

cache:
  directories:
    - $HOME/.cache/pypoetry
    - $HOME/.cache/pip

# command to install dependencies
install:
  - make install

# Run jobs for CI
jobs:
    include:
      - stage: "Lint"
        name: "Linting using Ruff"
        script: make lint

      - stage: "Testing"
        name: "Unit Testing"
        script: make test
#      - stage: "Build"
#        name: "Build"
#        script: poetry build
#      - stage: "Deploy"
#        name: "Deploy"
#        script: poetry publish --username $PYPI_USERNAME --password $PYPI_PASSWORD
