# Travis CI/CD configuration file
language: python
python:
  - "3.9"
#  - "python-nightly"

before_install:
  - curl -sSL https://install.python-poetry.org | python -
  - export PATH="$HOME/.poetry/bin:$PATH"
  - cd $TRAVIS_BUILD_DIR && echo $TRAVIS_BUILD_DIR

cache:
  directories:
    - $HOME/.cache/pypoetry
    - $HOME/.cache/pip

# command to install dependencies
install:
  - make install

# command to run tests
script:
  - make test

addons:
  apt:
    packages:
    - make
